### ISSUE TITLE
Parse textual content that contain tags properly

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/sts-ruby#2]
TBX-ISO-TML contains elements that include XML tagged content inside text.

The textual elements we need to support are:
* basicText
* highlight-elements
* simpleText

These elements are re-used inside elements such as in the ones that follow.

### Definition

<img width="746" alt="Screenshot 2023-11-29 at 3 45 30 PM" src="https://github.com/metanorma/sts-ruby/assets/11865/44244e3d-e07c-4ddb-8521-5dffc9a1d222">

### entailedTerm

<img width="732" alt="Screenshot 2023-11-29 at 3 46 43 PM" src="https://github.com/metanorma/sts-ruby/assets/11865/2fca2f0f-fbc5-4802-b25f-4f10f88aacaa">

### example
<img width="755" alt="Screenshot 2023-11-29 at 3 47 01 PM" src="https://github.com/metanorma/sts-ruby/assets/11865/de575c62-f89b-489d-9801-f5f61408b411">

### note
<img width="753" alt="Screenshot 2023-11-29 at 3 47 15 PM" src="https://github.com/metanorma/sts-ruby/assets/11865/7ca9b631-2792-4f5d-978a-de6c5b741d79">

## Conclusion

Once this is implemented, the commented out test for round-tripping shall pass.

**Comment by ronaldtse** [comment]
A summary:

<img width="736" alt="Screenshot 2023-11-29 at 3 49 22 PM" src="https://github.com/metanorma/sts-ruby/assets/11865/4d8063a0-b6a3-4f19-b188-f9771af94229">

**Comment by HassanAkbar** [comment]
@ronaldtse I’ve updated the code to read the tags that contain text mixed with tags & test cases are passing now.
There are 2 folders in this gem, namely `niso_sts` and `tbx_iso_tml`.
I have to add many new files to read the tags and I’m unsure in which directory I should add them. Can you explain how we are organizing the code?

**Comment by ronaldtse** [comment]
I actually want to separate the classes for NISO STS and TBX ISO TML. So for the classes for this ticket they should go into the tbx folder.

**Comment by HassanAkbar** [comment]
@ronaldtse to make the test case pass for the given test file [tbx-nisosts-0.2-formatted.xml](https://github.com/metanorma/sts-ruby/blob/main/spec/fixtures/tbx-nisosts-0.2-formatted.xml) I had to use the classes from both folders so I think we should create a separate folder for common files?

**Comment by ronaldtse** [comment]
@HassanAkbar can you make a PR so I can see? What are the common files?
